command_timeout = 10000

format = """
$username\
$hostname\
$os\
$shell\
$directory\
$sudo\
\n$character"""

right_format = """
$docker_context\
$conda\
$python\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$time
"""

[username]
show_always = true
format = "[$user]($style)"
style_user = 'bold #a6e22e'

[hostname]
ssh_symbol = " "
ssh_only = false
format = "@[$hostname](bold #9e6ffe) "

[os]
disabled = false
style = "bold #50a4db"

[localip]
ssh_only = true
format = '@[$localipv4](bold red) '
disabled = false
style = '#ff669d'

[shell]
fish_indicator = " "
bash_indicator = 'bsh'
zsh_indicator = 'zsh'
style = "#ff669d"
disabled = false

[sudo]
format = '[$symbol]($style)'
style = 'bold orange'
symbol = '󰚑 '
disabled = false

[directory]
read_only = " 🔒"
truncation_length = 3
truncate_to_repo = true
format = "[$path](#beed5f) "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"

# Git Branch
[git_branch]
symbol = " "
format = "on [$branch]($style) "

# Git Commit
[git_commit]
format = "([$hash]($style)) "

# Git Status
[git_status]
format = '[\[$all_status$ahead_behind\]]($style) '
style = "bold red"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
format = " [ $duration](#e6db74) "

[time]
format = "[󰥔 $time](bold #fd971f) "
time_format = "%R"
disabled = false


[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "
format = '[$symbol$environment](dimmed green) '

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
format = ' [🐋](blue bold)'

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
format = "[$symbol $version]($style) "
symbol = " "

[rlang]
format = 'with [📐 $version](blue bold) '
symbol = "󰟔 "


[rust]
symbol = " "
